services:
  docker-s3-mount:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - ${MOUNT_POINT}:/mnt:shared
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
    command: mkdir -p /mnt/$S3_BUCKET && mount-s3 -f $S3_BUCKET /mnt/$S3_BUCKET --allow-other